name: NLU Regression
on: [pull_request]
jobs:
  unit:
    name: BPDS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Copy test script + Check node version
        run: |
          cp build/nlu-regression.js .
          node -v
      - name: Fetch Node Packages
        run: |
          yarn --verbose
      - name: Build core, UI and modules
        run: |
          NODE_OPTIONS="--max-old-space-size=6000" yarn build
      - name: Run Regression Test
        run: |
          NLU_SEED=42 yarn start & sleep 5s &&
          node nlu-regression.js
