name: NLU Regression
on: [pull_request]
jobs:
  unit:
    name: BPDS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Test12345
        run: |
          echo "current dir : \n"
          pwd
          echo "build dir : \n"
          ls -l /home/runner/work/botpress/botpress/build/
          echo "botpress dir : \n"
          ls -l /home/runner/work/botpress/botpress
          echo "current again : \n"
          ls -l .
      - name: Fetch Node Packages
        run: |
          yarn --verbose
      - name: Build core, NLU and NLU-Testing
        run: |
          NODE_OPTIONS="--max-old-space-size=6000" yarn cmd build:core
          yarn cmd build:shared
          yarn cmd init:studio
          yarn cmd build:modules --m nlu,nlu-testing
      - name: Run Regression Test
        run: |
          NLU_SEED=42 yarn start & sleep 20s &&
          node build/nlu-regression.js
